apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    description: |
      Generate a new unique image tag based on format YYYY-MM-YY-HH-MM-SS.
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"tekton.dev/v1beta1","kind":"Task","metadata":{"annotations":{"description":"Generate
      a new unique image tag based on format
      YYYY-MM-YY-HH-MM-SS.\n"},"name":"generate-tag","namespace":"spring-pipeline"},"spec":{"results":[{"description":"The
      current date in human readable
      format","name":"image-tag"}],"steps":[{"image":"registry.access.redhat.com/ubi8/ubi-minimal:8.5","name":"generate-image-tag","script":"#!/usr/bin/env
      bash\ndate +\"%Y-%m-%d-%H-%M-%S\" | tee /tmp/date.txt\n# Trim the string
      to remove newline from the end\ntr --delete '\\n' \u003c/tmp/date.txt
      \u003e$(results.image-tag.path)\n"}]}}
  creationTimestamp: '2022-06-14T03:50:33Z'
  generation: 1
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:description': {}
        'f:spec':
          .: {}
          'f:results': {}
      manager: Mozilla
      operation: Update
      time: '2022-06-14T03:50:33Z'
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          'f:steps': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2022-06-14T03:54:41Z'
  name: generate-tag
  namespace: spring-pipeline
  resourceVersion: '49195'
  uid: 4f9eba8c-287f-426e-aa79-314fddc653b1
spec:
  results:
    - description: The current date in human readable format
      name: image-tag
  steps:
    - image: 'registry.access.redhat.com/ubi8/ubi-minimal:8.5'
      name: generate-image-tag
      resources: {}
      script: |
        #!/usr/bin/env bash
        date +"%Y-%m-%d-%H-%M-%S" | tee /tmp/date.txt
        # Trim the string to remove newline from the end
        tr --delete '\n' </tmp/date.txt >$(results.image-tag.path)
