apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  creationTimestamp: '2022-06-14T14:21:45Z'
  generation: 4
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:params': {}
          'f:steps': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2022-06-14T15:10:42Z'
  name: update-deployment
  namespace: spring-pipeline
  resourceVersion: '692489'
  uid: 0db730dd-995f-4164-aab3-d64dd6e7d306
spec:
  params:
    - description: The name of the deployment patch the image
      name: deployment
      type: string
    - description: Location of image to be patched with
      name: IMAGE
      type: string
  steps:
    - args:
        - >-
          oc patch deployment $(inputs.params.deployment)
          --patch='{"spec":{"template":{"spec":{
            "containers":[{
              "name": "$(inputs.params.deployment)",
              "image":"$(inputs.params.IMAGE)"
            }]
          }}}}'
      command:
        - /bin/bash
        - '-c'
      image: 'quay.io/openshift/origin-cli:latest'
      name: patch
      resources: {}
  workspaces:
    - name: source