kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workspaces
  namespace: spring-pipeline
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2-csi
  volumeMode: Filesystem

